FROM python:3.13-slim

ARG HSR_UI_PORT=8501

ENV HSR_UI_PORT=${HSR_UI_PORT} \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir streamlit python-dotenv requests

# COPY src ./src
# ENV PYTHONPATH=/app/src
COPY src/ui ./ui
ENV PYTHONPATH=/app

EXPOSE ${HSR_UI_PORT}

CMD ["sh", "-c", "streamlit run ui/main.py --server.address 0.0.0.0 --server.port ${HSR_UI_PORT}"]
